
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'p:\xe1\xa6!\x1a\x97\\\xf5\xb1\n\xfb\xfaj\xae\xef'
    
_lr_action_items = {'AND':([0,12,14,16,18,28,29,31,32,34,],[1,1,1,1,1,1,1,1,1,1,]),'ALL':([0,12,14,16,18,28,29,31,32,34,],[2,2,2,2,2,2,2,2,2,2,]),'RP':([8,22,27,30,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,],[-2,30,36,-3,-9,44,45,46,47,48,49,50,-4,-7,-6,-8,-11,-5,-10,]),'NEG':([0,12,14,16,18,28,29,31,32,34,],[4,4,4,4,4,4,4,4,4,4,]),'SOME':([0,12,14,16,18,28,29,31,32,34,],[5,5,5,5,5,5,5,5,5,5,]),'IMP':([0,12,14,16,18,28,29,31,32,34,],[7,7,7,7,7,7,7,7,7,7,]),'COMMA':([8,20,21,23,24,25,26,27,30,36,44,45,46,47,48,49,50,],[-2,28,29,31,32,33,34,35,-3,-9,-4,-7,-6,-8,-11,-5,-10,]),'LP':([1,2,4,5,7,9,10,11,],[12,13,14,15,16,17,18,19,]),'PRED':([0,12,14,16,18,28,29,31,32,34,],[11,11,11,11,11,11,11,11,11,11,]),'VAR':([13,15,17,19,33,35,],[21,23,25,27,41,43,]),'EQ':([0,12,14,16,18,28,29,31,32,34,],[9,9,9,9,9,9,9,9,9,9,]),'OR':([0,12,14,16,18,28,29,31,32,34,],[10,10,10,10,10,10,10,10,10,10,]),'$end':([3,6,8,30,36,44,45,46,47,48,49,50,],[-1,0,-2,-3,-9,-4,-7,-6,-8,-11,-5,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cfor':([0,],[6,]),'for':([0,12,14,16,18,28,29,31,32,34,],[3,20,22,24,26,37,38,39,40,42,]),'atom':([0,12,14,16,18,28,29,31,32,34,],[8,8,8,8,8,8,8,8,8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cfor","S'",1,None,None,None),
  ('cfor -> for','cfor',1,'p_Ter','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',179),
  ('for -> atom','for',1,'p_forAt','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',184),
  ('for -> NEG LP for RP','for',4,'p_forNEG2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',190),
  ('for -> AND LP for COMMA for RP','for',6,'p_forAND2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',196),
  ('for -> OR LP for COMMA for RP','for',6,'p_forOR2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',202),
  ('for -> SOME LP VAR COMMA for RP','for',6,'p_forSOME2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',208),
  ('for -> ALL LP VAR COMMA for RP','for',6,'p_forALL2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',214),
  ('for -> IMP LP for COMMA for RP','for',6,'p_forIMP2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',221),
  ('atom -> PRED LP VAR RP','atom',4,'p_atom1','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',232),
  ('atom -> PRED LP VAR COMMA VAR RP','atom',6,'p_atom2','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',236),
  ('atom -> EQ LP VAR COMMA VAR RP','atom',6,'p_atom3','/Users/camilothorne/workspace2/boxer/new-boxer2fol/normalizer.py',240),
]
